before_scripts:
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
  - tar -xvf /tmp/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-9-2020-q2-update/bin

sudo: enabled

language: cpp

os: linux

script:
    - make

    