before_scripts:
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2
  - tar -xvf /tmp/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
  - export PATH=$PATH:$PWD/casperjs-1.0.2/bin/gcc-arm-none-eabi-9-2020-q2-update/bin

sudo: enabled

language: cpp

os: linux

script:
    - make