before_scripts:
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2?revision=05382cca-1721-44e1-ae19-1e7c3dc96118&la=en&hash=D7C9D18FCA2DD9F894FD9F3C3DC9228498FA281A -O /tmp/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
  - tar -xvf /tmp/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
  - export PATH=$PATH:$PWD/casperjs-1.0.2/bin/gcc-arm-none-eabi-9-2020-q2-update/bin
  
sudo: enabled

language: cpp

os: linux

script:
    - make